---
# defaults file for sonarqube
vm_max_map_count: 262144
fs_file-max: 65536
max_no_open_file_descriptors: 65536
max_no_of_user_processes: 4096

apt_packages:
- wget
- unzip
- openjdk-11-jdk
- openjdk-11-jre

postgres_username: postgres
linux_postgres_password: password